In [3]:
import pickle
import random
import re
import sklearn
from sklearn.feature_extraction.text import TfidfVectorizer
import numpy as np
import pandas as pd

ModuleNotFoundError: No module named 'sklearn'

In [2]:
import textblob

In [3]:
neg_data = pickle.load( open( "neg_data.p", "rb" ) )
pos_data = pickle.load( open( "pos_data.p", "rb" ) )

In [19]:
neg_data  = [[i, 1] for i in neg_data]
pos_data = [[i, 0] for i in pos_data]
print(neg_data[0], pos_data[0])

["\nMost shadow-related tools don't treat numeric ids as potential\nusernames, so change our behaviour to match that. Previously, using an\nexplicit specification like 111:222 could result in the UID and GID not\nbeing 111 and 222 respectively (which is confusing).\nFixes #695\nSigned-off-by: Aleksa Sarai asarai@suse.de\n\n@tianon I know it's been a while, but I've refactored most of the code you wrote a few years ago. Want to take a look? :P\n\n@dqminh Nits addressed. 😸\n\nOther than the fact that we're hitting   at least once per every line in both   and   unnecessarily, this LGTM (and I'm OK with the implementation if there isn't a clean way to switch that code) 👍\n\nThanks @cyphar !\n\n@tianon I've addressed your concern about calling   too many times per line. Merging.\n\nawesome, thanks all\n\n🤘\n\n          Numeric user id passed to --user interpreted as user name if user name is numeric in container  \n          #21436\n", 1] ['\nWhen the   environment variable is not set, the 

In [106]:
import nltk
from nltk.corpus import stopwords 
from nltk.tokenize import word_tokenize, sent_tokenize
from nltk.stem.porter import PorterStemmer
stop_words = set(stopwords.words('english')) 
stem = PorterStemmer()
vectorizer = TfidfVectorizer(stop_words = stop_words, use_idf=True, ngram_range=(1,3))

In [15]:
neg_data = pickle.load( open( "neg_data.p", "rb" ) )
pos_data = pickle.load( open( "pos_data.p", "rb" ) )

In [83]:
def preproces_doc(doc):
    filtered_sent = []
    for i in doc:
#         print(i)
        i = re.sub("[^A-Za-z0-9 ]+", '', i)
        word_lst = word_tokenize(i)
        filter_lst = [w for w in word_lst if not w in stop_words]
        stem_lst = [stem.stem(w) for w in filter_lst]
        filtered_sent.append(" ".join(stem_lst))
    return filtered_sent

In [ ]:
filter_neg_sent = preproces_doc(neg_data)
filter_pos_sent = preproces_doc(pos_data)

In [116]:
total_sent = filter_neg_sent+filter_pos_sent

In [275]:
tot

['most shadowrel tool dont treat numer id potentialusernam chang behaviour match previous use anexplicit specif like 111222 could result uid gid notb 111 222 respect confusingfix 695signedoffbi aleksa sarai asaraisusedetianon I know ive refactor code wrote year ago want take look pdqminh nit address other fact hit least per everi line unnecessarili lgtm Im OK implement isnt clean way switch code thank cyphar tianon ive address concern call mani time per line mergingawesom thank numer user id pass user interpret user name user name numer contain 21436',
 'the cooki current return openshift intern pod IP addressthi secur issu attack develop map podsin cluster observ return cookiethi chang return hash intern address intern servicenam obfusc intern inform the servic name configuredwhen servic creat visibl outsid user thisin combin intern ipport hash present thecookieaddress httpsbugzillaredhatcomshowbugcgiid1318796thi look much better lgtmcode lgtm If could also add addendpoint test httpsg

In [114]:
vectorizer.fit(total_sent)
# summarize
# encode document
vector = vectorizer.transform(total_sent)
# summarize encoded vector


In [115]:
print(vector.shape)
print(vector.toarray())

(245, 49335)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [119]:
vector.toarray()

array([0., 0., 0., ..., 0., 0., 0.])

In [122]:
corpus = np.append(np.array(filter_pos_sent), np.array(filter_neg_sent))

In [127]:
X = vectorizer.transform(corpus)

In [128]:
tf_idf_vector = X.toarray()
pos_tf_idf_vector = tf_idf_vector[:200]
neg_tf_idf_vector = tf_idf_vector[201: ]

In [222]:
pos_tag = [[i, 0] for i in pos_tf_idf_vector]  
neg_tag = [[i, 1] for i in neg_tf_idf_vector]  
final_corpus = pos_tag + neg_tag

In [151]:
type(final_corpus[0])

list

In [270]:
# for i in final_corpus.shape[0]:
#     final_corpus[i] = np.array(final_corpus[i])

In [210]:
# for i in final_corpus.shape[0]:
#     final_corpus[i] = final_corpus[i]

AttributeError: 'list' object has no attribute 'shape'

In [159]:
np.zeros((len(final_corpus),final_corpus[0][0].shape[0])).shape

(244, 49335)

In [160]:
from sklearn.naive_bayes import MultinomialNB, GaussianNB, BernoulliNB
from sklearn import metrics

In [146]:
clf = MultinomialNB().fit(X_train, y_train)

400

In [163]:
data = pd.DataFrame(final_corpus)

In [166]:
# data.columns = ['Para','label']

In [175]:
# X_data = data["Para"]
# Y_data = data["label"]

In [178]:
import random

In [223]:
random.shuffle(final_corpus)

In [224]:
for i in range(len(final_corpus)):
    final_corpus[0][0] = final_corpus[0][0][:]

In [225]:
final_corpus[0]

[array([0., 0., 0., ..., 0., 0., 0.]), 0]

In [246]:
train = final_corpus[:-30]

In [247]:
test = final_corpus[-30:]

[[array([0., 0., 0., ..., 0., 0., 0.]), 0],
 [array([0., 0., 0., ..., 0., 0., 0.]), 0],
 [array([0., 0., 0., ..., 0., 0., 0.]), 0],
 [array([0., 0., 0., ..., 0., 0., 0.]), 0],
 [array([0., 0., 0., ..., 0., 0., 0.]), 1],
 [array([0., 0., 0., ..., 0., 0., 0.]), 0],
 [array([0., 0., 0., ..., 0., 0., 0.]), 0],
 [array([0., 0., 0., ..., 0., 0., 0.]), 1],
 [array([0., 0., 0., ..., 0., 0., 0.]), 0],
 [array([0., 0., 0., ..., 0., 0., 0.]), 0],
 [array([0., 0., 0., ..., 0., 0., 0.]), 0],
 [array([0., 0., 0., ..., 0., 0., 0.]), 0],
 [array([0., 0., 0., ..., 0., 0., 0.]), 0],
 [array([0., 0., 0., ..., 0., 0., 0.]), 0],
 [array([0., 0., 0., ..., 0., 0., 0.]), 0],
 [array([0., 0., 0., ..., 0., 0., 0.]), 1],
 [array([0., 0., 0., ..., 0., 0., 0.]), 0],
 [array([0., 0., 0., ..., 0., 0., 0.]), 1],
 [array([0., 0., 0., ..., 0., 0., 0.]), 0],
 [array([0., 0., 0., ..., 0., 0., 0.]), 0],
 [array([0., 0., 0., ..., 0., 0., 0.]), 0],
 [array([0., 0., 0., ..., 0., 0., 0.]), 0],
 [array([0., 0., 0., ..., 0., 0.

In [249]:
train = np.array(train)
test = np.array(test)

In [250]:
x_train = train[:,0]
y_train = train[:,1]
x_test = test[:,0]
y_test = test[:,1]

In [251]:
def convert(x_train):
    temp_1 = x_train[0]
    for i in x_train:
        temp_1 = np.vstack([temp_1, i])
    temp_1 = temp_1[1:]
    return temp_1

In [252]:
y_train = y_train.astype('int')
y_test = y_test.astype("int")

In [261]:
x_Train = convert(x_train)
x_Test = convert(x_test)

In [264]:
clf = MultinomialNB().fit(x_Train, y_train)

In [266]:
predicted = clf.predict(x_Test)

In [267]:
print("MultinomialNB Accuracy:",metrics.accuracy_score(y_test, predicted))

MultinomialNB Accuracy: 0.8333333333333334


In [268]:
predicted

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0])

In [269]:
y_test

array([0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1])

In [271]:
from textblob.classifiers import NaiveBayesClassifier

ModuleNotFoundError: No module named 'textblob'

In [274]:
pickle.dump([x_Train,x_Test,y_train,y_test],open("train.p","wb"))

In [ ]:
filter_neg_labset = [[i, 1] for i in filter_neg_sent]
filter_pos_labset = [[i, 0] for i in filter_pos_sent]
new_neg_data = new_wordy(neg_data)
new_pos_data = new_wordy(pos_data)

In [ ]:
new_neg_data = new_wordy(neg_data)
new_pos_data = new_wordy(pos_data)

["Most shadow-related tools do n't treat numeric ids as potential usernames , so change our behaviour to match that . Previously , using an explicit specification like 111:222 could result in the UID and GID not being 111 and 222 respectively ( which is confusing ) . Fixes # 695 Signed-off-by : Aleksa Sarai asarai @ suse.de @ tianon I know it 's been a while , but I 've refactored most of the code you wrote a few years ago . Want to take a look ? : P @ dqminh Nits addressed . 😸 Other than the fact that we 're hitting at least once per every line in both and unnecessarily , this LGTM ( and I 'm OK with the implementation if there is n't a clean way to switch that code ) 👍 Thanks @ cyphar ! @ tianon I 've addressed your concern about calling too many times per line . Merging . awesome , thanks all 🤘 Numeric user id passed to -- user interpreted as user name if user name is numeric in container # 21436",
 "The cookie currently returns the openshift internal pod IP address . This is a secu

In [20]:
total_data = pos_data+neg_data
random.shuffle(total_data)

["\nI am building and testing k8s-policy v0.6.0 from source. Because I am trying to use Calico with K8s v1.6.x, so i have been testing the policy-control with k8s v1.6.x image.\nThe following is the code change to Makefile\n \nThen issuing  , I got following error\n \n\nAdding @neiljerram who wrote the test.\nThese tests don't currently seem to work on a mac, so will need to do some work in order to reproduce.\n\nI guess the key thing here is\n \nand that it's because we don't yet have any RBAC in that test.\nIs there some option that we can add to the\n \nline to tell the API server not to bother with RBAC?\n\nHi @neiljerram, according to https://kubernetes.io/docs/admin/authorization/#using-flags-for-your-authorization-module, I have tried to add\n \nto apiserver command, but that doesn't resolve the problem.\n\nThanks @levivic   It must be a different problem then; I will continue investigating.\n\n@levivic @caseydavenport FYI here is how I fixed a similar problem in the Felix repo:

(('\nThe chainer component should be using an image tagged 0.3 for the 0.3. release.\nCurrently its using the "latest" tag:\nhttps://github.com/kubeflow/kubeflow/blob/master/kubeflow/chainer-job/prototypes/chainer-operator.jsonnet#L6\nIdeally the image would be published to gcr.io/kubeflow-images-public as well.\n\n@everpeace Can you pick this up?\n\n@jlewi Sure, I will.\n\nTrackers:\n\n DONE: add chainer to kubeflow releaser (xref: kubeflow/kubeflow#1549)\n DONE: Publishing docker image in prow (in postsubmit) (xref: #26)\n DONE:  Tag and update v0.3.0 release for chainer-operator (xref: kubeflow/kubeflow#1552)\n\n\nHow\'s this coming?\nThis week we revamped our image auto release process. So the chainer postsubmits should now be able to build and push an image to gcr.io/kubeflow-images-public.\nI added updated instructions here:\nhttps://github.com/kubeflow/kubeflow/blob/master/docs_dev/releasing.md#image-auto-release\nUnfortunately this means there is a bit of churn. i.e. the releas